# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Maximilian Ludvigsson'
tagline:          'blogg'
description:      'Om utbytesåret i Taiwan.'
url:              #
baseurl:          '/'
paginate:         5

author:
  name:           'Maximilian Ludvigsson'
  url:            https://instagram.com/mludv

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
