# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Svarta linjer'
tagline:          'blogg'
description:      'Maximilian Ludvigssons blogg.'
url:              'http://svartalinjer.com'
baseurl:          '/'
paginate:         5

author:
  name:           'Maximilian Ludvigsson'
  url:            https://instagram.com/mludv

